build-gleam:
	gleam build --target erlang
	gleam build --target javascript
	rm -f ./build/dev/erlang/gleam_stdlib/_gleam_artefacts/gleam@@compile.erl
	rm -f ./build/dev/erlang/shared_gleam/_gleam_artefacts/gleam@@compile.erl